name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name:  ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'

      - name: 📦 Get Flutter Dependencies
        working-directory: example
        run: flutter pub get

      - name: 👷 Build Flutter Web App
        working-directory: example
        run: flutter build web --release --base-href /sheets/

      - name: ☁️ Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: example/build/web
          publish_branch: gh-pages
